//
// Created by Howard Colin on 04/01/2023.
//
#include <iostream>
#include "../../xxhash_generator.h"

using namespace std;
namespace fs = std::filesystem;

//compare calc_xxh result to the result generated by xxhsum

int test_xxhash() {
    int err_code = 0;
    xxhash_generator test_gen;
    fs::path sample_file = "xxh_sample";

    uint64_t sample_h = 0xef46db3751d8e999;

    if(test_gen.calc_xxh(sample_file) != 0) {
        err_code += 1;
    }

    if(test_gen.get_hash() != sample_h){
        err_code = 1;
        cout << "HASH TEST FAILED - REFERENCE: ";
        cout << setfill('0') << setw(16) << std::hex << sample_h << " : ";
        cout << "CALCULATED: ";
        cout << setfill('0') << setw(16) << std::hex << test_gen.get_hash() << std::endl;
    };

    return err_code;
}

int main() {
    return test_xxhash();
}